### PR TITLE
[NPS-7379] Fix the double dependencies tag in the pom file

### PR DESCRIPTION
**Pull request by youminhan**
1. Fix the issue of showing two "dependencies" tag in the pom file when packaging the spark connector.
2. Pass all the tests for spark connector.

Signed-off-by: Youmin Han <Youmin.Han@dell.com>

### CODE REVIEW

**Comment by maddisondavid** [comment]
Can the new POM be attached to the PR as proof that this fixes the double dependency issue?

**Comment by youminhan** [comment]
Here is the content of the POM file. You can also download the zip for the POM built by gradlew. 
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.pravega</groupId>
  <artifactId>pravega-connectors-spark</artifactId>
  <version>0.7.0-SNAPSHOT</version>
  <name>Pravega Spark Connectors</name>
  <description>Streaming Storage Platform</description>
  <url>http://pravega.io</url>
  <licenses>
    <license>
      <name>The Apache License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>
  <scm>
    <connection>scm:git:git://github.com/pravega/spark-connectors.git</connection>
    <developerConnection>scm:git:https://github.com/pravega/spark-connectors.git</developerConnection>
    <url>https://github.com/pravega/spark-connectors/tree/master</url>
  </scm>
  <dependencies>
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-sql_2.11</artifactId>
      <version>2.4.6</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</project>
```
[pravega-connectors-spark-0.7.0-SNAPSHOT.zip](https://github.com/pravega/spark-connectors/files/5283972/pravega-connectors-spark-0.7.0-SNAPSHOT.zip)

**Review by maddisondavid — APPROVED** [review]
LGTM

**Review by crazyzhou — CHANGES_REQUESTED** [review]
The code change itself LGTM. However, @youminhan Note this is the first commit after the open source, it triggers the travis build for our first time, so we should also need to fix it too. This travis build fails for using the [oracle jdk](https://github.com/pravega/spark-connectors/blob/68628b90b51c99d14bf5c9fc154b59a88e61b2ab/.travis.yml#L13), try to use the openjdk to let it pass, and I'm looking forward to our first open snapshot artifact.

**Review by crazyzhou — APPROVED** [review]
LGTM

**Pull request merged**
